export const deadlines = [
  {
    "name": "ATC 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+360",
    "tags": ["#OPERATING SYSTEMS", "#STORAGE SYSTEMS", "#CLOUD COMPUTING"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-01-14",
    "notification": "2025-04-25",
    "conference_dates": "July 7-9, 2025",
    "location": "Boston, MA",
    "keywords": ["Operating Systems", "Cloud Computing", "Storage Systems", "File Systems", "Virtualization"]
  },
  {
    "name": "HotOS 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+359",
    "tags": ["#OPERATING SYSTEMS"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2025-01-15",
    "notification": "2025-04-01",
    "conference_dates": "May 14-16, 2025",
    "location": "Banff, Alberta",
    "keywords": ["Operating Systems", "Experimental Systems"]
  },
  {
    "name": "ISMM 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+304",
    "tags": ["#PROGRAMMING LANGUAGES", "#MEMORY MANAGEMENT"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2025-03-11",
    "notification": "2025-05-06",
    "conference_dates": "June 17, 2025",
    "location": "Seoul, South Korea",
    "keywords": ["Memory Management", "Runtime Systems", "Compilers"]
  },
  {
    "name": "ASPLOS 2025",
    "link": null,
    "cycle": "Spring",
    "dDay": "D+303",
    "tags": ["#COMPUTER ARCHITECTURE", "#OPERATING SYSTEMS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-03-12",
    "notification": "2025-06-24",
    "conference_dates": "March 22-26, 2026",
    "location": "Pittsburgh, PA",
    "keywords": ["Computer Architecture", "Operating Systems", "Compilers", "Hardware/Software Co-design"]
  },
  {
    "name": "MobiCom 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+297",
    "tags": ["#NETWORKING", "#MOBILE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-03-18",
    "notification": "2025-06-24",
    "conference_dates": "November 4-8, 2025",
    "location": "Washington, D.C.",
    "keywords": ["Mobile Systems", "Wireless Networking"]
  },
  {
    "name": "HotStorage 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+280",
    "tags": ["#STORAGE SYSTEMS"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2025-04-04",
    "notification": "2025-05-16",
    "conference_dates": "July 10-11, 2025",
    "location": "Boston, MA",
    "keywords": ["Storage Systems", "Non-volatile Memory", "File Systems"]
  },
  {
    "name": "MICRO 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+273",
    "tags": ["#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-04-11",
    "notification": "2025-07-14",
    "conference_dates": "October 18-22, 2025",
    "location": "Seoul, Korea",
    "keywords": ["Microarchitecture", "Hardware Accelerators", "Computer Architecture", "Instruction-level Parallelism"]
  },
  {
    "name": "RAID 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+260",
    "tags": ["#COMPUTER SECURITY"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-04-24",
    "notification": "2025-07-09",
    "conference_dates": "October 19-22, 2025",
    "location": "Ploen, Germany",
    "keywords": ["System Security", "Intrusion Detection", "Attack Analysis"]
  },
  {
    "name": "HotNets 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+184",
    "tags": ["#NETWORKING"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2025-07-09",
    "notification": "2025-09-17",
    "conference_dates": "November 17-18, 2025",
    "location": "College Park, MD",
    "keywords": ["Network Architecture", "Experimental Networking"]
  },
  {
    "name": "POPL 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+183",
    "tags": ["#PROGRAMMING LANGUAGES", "#ALGORITHMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-07-10",
    "notification": "2025-10-02",
    "conference_dates": "January 11-17, 2026",
    "location": "Chicago, IL",
    "keywords": ["Program Semantics", "Formal Methods", "Program Analysis", "Language Theory"]
  },
  {
    "name": "SoCC 2025",
    "link": null,
    "cycle": null,
    "dDay": "D+179",
    "tags": ["#CLOUD COMPUTING", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-07-14",
    "notification": "2025-09-26",
    "conference_dates": "November 19-21, 2025",
    "location": "Virtual event",
    "keywords": ["Cloud Computing", "Distributed Databases", "Resource Management"]
  },
  {
    "name": "SIGMETRICS 2025",
    "link": null,
    "cycle": "Summer",
    "dDay": "D+164",
    "tags": ["#PERFORMANCE", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-07-29",
    "notification": "2025-09-26",
    "conference_dates": "June 8-12, 2026",
    "location": "Ann Arbor, MI",
    "keywords": ["Performance Evaluation", "Workload Characterization", "Analytical Modeling"]
  },
  {
    "name": "INFOCOM 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+162",
    "tags": ["#NETWORKING", "#WIRELESS NETWORKING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-07-31",
    "notification": "2025-12-08",
    "conference_dates": "May 18-21, 2026",
    "location": "Paris, France",
    "keywords": ["Computer Networks", "Wireless Networking", "Network Theory", "Network Protocols"]
  },
  {
    "name": "HPCA 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+161",
    "tags": ["#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-08-01",
    "notification": "2025-11-07",
    "conference_dates": "January 31 - February 4, 2026",
    "location": "Sydney, Australia",
    "keywords": ["Computer Architecture", "Memory Hierarchy", "Multi-core", "Hardware Accelerators"]
  },
  {
    "name": "NDSS 2026",
    "link": null,
    "cycle": "Fall",
    "dDay": "D+156",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-08-06",
    "notification": "2025-10-22",
    "conference_dates": "February 23-27, 2026",
    "location": "San Diego, CA",
    "keywords": ["Network Security", "System Security", "Web Security"]
  },
  {
    "name": "ASPLOS 2026",
    "link": null,
    "cycle": "Summer",
    "dDay": "D+142",
    "tags": ["#COMPUTER ARCHITECTURE", "#OPERATING SYSTEMS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-08-20",
    "notification": "2025-11-24",
    "conference_dates": "March 22-26, 2026",
    "location": "Pittsburgh, PA",
    "keywords": ["Computer Architecture", "Operating Systems", "Compilers", "Hardware/Software Co-design"]
  },
  {
    "name": "AsiaCCS 2026",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D+137",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-08-25",
    "notification": "2025-11-19",
    "conference_dates": "June 1-6, 2026",
    "location": "Bangalore, India",
    "keywords": ["Information Security", "Network Security", "Privacy"]
  },
  {
    "name": "Usenix Security 2026",
    "link": null,
    "cycle": "Fall",
    "dDay": "D+136",
    "tags": ["#COMPUTER SECURITY", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-08-26",
    "notification": "2025-12-04",
    "conference_dates": "August 12-14, 2026",
    "location": "Baltimore, MD",
    "keywords": ["System Security", "Network Security", "Privacy", "Software Security"]
  },
  {
    "name": "PPoPP 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+130",
    "tags": ["#PARALLEL COMPUTING", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-09-01",
    "notification": "2025-11-10",
    "conference_dates": "January 31 - February 4, 2026",
    "location": "Sydney, Australia",
    "keywords": ["Parallel Programming", "Concurrency", "Runtime Systems"]
  },
  {
    "name": "CGO 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+120",
    "tags": ["#COMPILERS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-09-11",
    "notification": "2025-11-03",
    "conference_dates": "January 31 - February 4, 2026",
    "location": "Sydney, Australia",
    "keywords": ["Compiler Optimization", "Code Generation", "Binary Analysis"]
  },
  {
    "name": "NSDI 2026",
    "link": null,
    "cycle": "Fall",
    "dDay": "D+113",
    "tags": ["#NETWORKED SYSTEMS", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-09-18",
    "notification": "2025-12-09",
    "conference_dates": "May 4-6, 2026",
    "location": "Renton, WA",
    "keywords": ["Networked Systems", "Cloud Networking", "Datacenters", "Distributed Systems"]
  },
  {
    "name": "IPDPS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+92",
    "tags": ["#PARALLEL COMPUTING", "#HIGH-PERFORMANCE COMPUTING"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-10-09",
    "notification": "2025-12-18",
    "conference_dates": "May 25-29, 2026",
    "location": "New Orleans, LA",
    "keywords": ["Parallel Computing", "Parallel Algorithms", "High-Performance Computing"]
  },
  {
    "name": "OOPSLA 2026",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D+91",
    "tags": ["#PROGRAMMING LANGUAGES", "#SOFTWARE ENGINEERING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-10-10",
    "notification": "2025-12-17",
    "conference_dates": "October 3-9, 2026",
    "location": "Oakland, CA",
    "keywords": ["Programming Models", "Software Engineering", "Language Design"]
  },
  {
    "name": "HotMobile 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+70",
    "tags": ["#MOBILE SYSTEMS"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2025-10-31",
    "notification": "2025-12-16",
    "conference_dates": "February 25-26, 2026",
    "location": "Atlanta, GA",
    "keywords": ["Mobile Systems", "Ubiquitous Computing"]
  },
  {
    "name": "CC 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+60",
    "tags": ["#COMPILERS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-11-10",
    "notification": "2025-12-10",
    "conference_dates": "January 31 - February 1, 2026",
    "location": "Sydney, Australia",
    "keywords": ["Compiler Construction", "Language Translation", "Compiler Optimization"]
  },
  {
    "name": "PLDI 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+57",
    "tags": ["#PROGRAMMING LANGUAGES", "#COMPILERS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-11-13",
    "notification": "2026-03-05",
    "conference_dates": "June 15-19, 2026",
    "location": "Boulder, CO",
    "keywords": ["Compiler Optimization", "Program Analysis", "Compilers", "Language Design"]
  },
  {
    "name": "IEEE S&P 2026",
    "link": null,
    "cycle": "Winter",
    "dDay": "D+57",
    "tags": ["#COMPUTER SECURITY"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-11-13",
    "notification": "2026-03-09",
    "conference_dates": "May 18-21, 2026",
    "location": "San Francisco, CA",
    "keywords": ["System Security", "Privacy", "Cryptography", "Computer Security"]
  },
  {
    "name": "RTAS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+57",
    "tags": ["#REAL-TIME SYSTEMS", "#EMBEDDED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-11-13",
    "notification": "2026-01-29",
    "conference_dates": "May 12-14, 2026",
    "location": "Saint Malo, France",
    "keywords": ["Real-Time Systems", "Embedded Systems", "Cyber-Physical Systems"]
  },
  {
    "name": "ISCA 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+53",
    "tags": ["#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-11-17",
    "notification": "2026-03-27",
    "conference_dates": "June 27 - July 1, 2026",
    "location": "Raleigh, NC",
    "keywords": [" Purely listed as: Computer Architecture", "Memory Systems", "Hardware/Software Co-design"]
  },
  {
    "name": "DAC 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+51",
    "tags": ["#HARDWARE", "#DESIGN AUTOMATION"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2025-11-11",
    "deadline": "2025-11-19",
    "notification": "2026-03-09",
    "conference_dates": "July 26-29, 2026",
    "location": "Long Beach, CA",
    "keywords": ["Electronic Design Automation", "Hardware Security", "System Design", "VLSI"]
  },
  {
    "name": "DSN 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+36",
    "tags": ["#DISTRIBUTED SYSTEMS", "#COMPUTER SECURITY"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-04",
    "notification": "2026-03-19",
    "conference_dates": "June 22-25, 2026",
    "location": "Budapest, Hungary",
    "keywords": ["Fault Tolerance", "Dependable Systems", "System Security"]
  },
  {
    "name": "Middleware 2026",
    "link": null,
    "cycle": "Winter",
    "dDay": "D+29",
    "tags": ["#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-11",
    "notification": "2026-03-06",
    "conference_dates": "November 30 - December 4, 2026",
    "location": "Tarragona, Spain",
    "keywords": ["Distributed Systems", "Middleware", "Edge Computing"]
  },
  {
    "name": "OSDI 2026",
    "link": null,
    "cycle": "annual",
    "dDay": "D+29",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS", "#STORAGE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-11",
    "notification": "2026-03-26",
    "conference_dates": "July 13-15, 2026",
    "location": "Seattle, WA",
    "keywords": ["Operating Systems", "Distributed Systems", "Storage Systems", "Cloud Computing", "Reliability"]
  },
  {
    "name": "CoNEXT 2026",
    "link": null,
    "cycle": "Winter",
    "dDay": "D+29",
    "tags": ["#NETWORKING"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-11",
    "notification": "2025-12-08",
    "conference_dates": "December 7-10, 2026",
    "location": "Utrecht, The Netherlands",
    "keywords": ["Network Protocols", "Traffic Analysis", "Internet Architecture"]
  },
  {
    "name": "AsiaCCS 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D+28",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-12",
    "notification": "2026-03-10",
    "conference_dates": "June 1-6, 2026",
    "location": "Bangalore, India",
    "keywords": ["Information Security", "Network Security", "Privacy"]
  },
  {
    "name": "ISPASS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+28",
    "tags": ["#COMPUTER ARCHITECTURE", "#PERFORMANCE"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-12",
    "notification": null,
    "conference_dates": "April 2026",
    "location": "Seoul, South Korea",
    "keywords": ["Performance Evaluation", "Computer Architecture", "Workload Characterization", "Simulation"]
  },
  {
    "name": "ICDCS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D+28",
    "tags": ["#DISTRIBUTED SYSTEMS", "#NETWORKING"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-12",
    "notification": null,
    "conference_dates": "July 2026",
    "location": "South Korea",
    "keywords": ["Distributed Systems", "Cloud Computing", "Distributed Algorithms"]
  },
  {
    "name": "ICS 2026",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D+24",
    "tags": ["#HIGH-PERFORMANCE COMPUTING", "#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2025-12-16",
    "notification": "March 2026",
    "conference_dates": "July 6-9, 2026",
    "location": "Belfast, UK",
    "keywords": ["High-Performance Computing", "Computer Architecture", "Parallel Computing", "Supercomputing"]
  },
  {
    "name": "SIGMETRICS 2026",
    "link": null,
    "cycle": "Winter",
    "dDay": "D-4",
    "tags": ["#PERFORMANCE", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-01-13",
    "notification": "2026-03-13",
    "conference_dates": "June 8-12, 2026",
    "location": "Ann Arbor, MI",
    "keywords": ["Performance Evaluation", "Workload Characterization", "Analytical Modeling"]
  },
  {
    "name": "CCS 2026",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D-5",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-01-07",
    "deadline": "2026-01-14",
    "notification": "2026-04-09",
    "conference_dates": "November 15-19, 2026",
    "location": "The Hague, The Netherlands",
    "keywords": ["Computer Security", "Network Security", "Privacy", "Cryptography"],
    "extra": { "early_reject": "2026-02-20" }
  },
  {
    "name": "SIGMOD 2027",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D-1 (Abstract)",
    "tags": ["#DATA MANAGEMENT", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-01-10",
    "deadline": "2026-01-17",
    "notification": "2026-04-19",
    "conference_dates": "June 13-19, 2027",
    "location": "Huntington Beach, CA",
    "keywords": ["Databases", "Data Management", "Data Systems", "Scalable Data Processing"]
  },
  {
    "name": "CF 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-10",
    "tags": ["#COMPUTER ARCHITECTURE", "#EMBEDDED SYSTEMS"],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": null,
    "deadline": "2026-01-19",
    "notification": "2026-03-09",
    "conference_dates": "May 19-21, 2026",
    "location": "Catania, Sicily, Italy",
    "keywords": ["Hardware Accelerators", "Embedded Systems", "Hardware/Software Co-design", "Computer Architecture"]
  },
  {
    "name": "ICML 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-14 (Abstract)",
    "tags": ["#MACHINE LEARNING", "#DEEP LEARNING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-01-23",
    "deadline": "2026-01-28",
    "notification": "May 2026",
    "conference_dates": "July 6-11, 2026",
    "location": "Seoul, South Korea",
    "keywords": ["Deep Learning", "Reinforcement Learning", "AI", "Neural Networks"]
  },
  {
    "name": "Usenix Security 2026",
    "link": null,
    "cycle": "Winter",
    "dDay": "D-20 (Abstract)",
    "tags": ["#COMPUTER SECURITY", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-01-29",
    "deadline": "2026-02-05",
    "notification": "2026-05-14",
    "conference_dates": "August 12-14, 2026",
    "location": "Baltimore, MD",
    "keywords": ["System Security", "Network Security", "Privacy", "Software Security"]
  },
  {
    "name": "SIGCOMM 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-21 (Abstract)",
    "tags": ["#NETWORKING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-01-30",
    "deadline": "2026-02-06",
    "notification": "April 2026",
    "conference_dates": "August 2026",
    "location": "Denver, CO",
    "keywords": ["Network Architecture", "Network Protocols", "Internet Measurement"]
  },
  {
    "name": "HPDC 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-20 (Abstract)",
    "tags": ["#DISTRIBUTED SYSTEMS", "#HIGH-PERFORMANCE COMPUTING"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": "2026-01-29",
    "deadline": "2026-02-06",
    "notification": "2026-03-31",
    "conference_dates": "July 13-16, 2026",
    "location": "Cleveland, OH",
    "keywords": ["Distributed Systems", "High-Performance Computing", "Cloud Computing", "Resource Management"]
  },
  {
    "name": "KDD 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-23 (Abstract)",
    "tags": ["#MACHINE LEARNING", "#DATA MINING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-02-01",
    "deadline": "2026-02-08",
    "notification": "2026-05-16",
    "conference_dates": "August 9-13, 2026",
    "location": "Jeju, South Korea",
    "keywords": ["Data Mining", "Machine Learning", "Knowledge Discovery", "Big Data"]
  },
  {
    "name": "ICS 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-24 (Abstract)",
    "tags": ["#HIGH-PERFORMANCE COMPUTING", "#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": "2026-02-02",
    "deadline": "2026-02-09",
    "notification": "2026-04-06",
    "conference_dates": "July 6-9, 2026",
    "location": "Belfast, UK",
    "keywords": ["High-Performance Computing", "Computer Architecture", "Parallel Computing", "Supercomputing"]
  },
  {
    "name": "ECRTS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-48",
    "tags": ["#REAL-TIME SYSTEMS", "#EMBEDDED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2026-02-26",
    "notification": "2026-04-20",
    "conference_dates": "July 7-10, 2026",
    "location": "Lund, Sweden",
    "keywords": ["Real-Time Systems", "Embedded Systems", "Scheduling Analysis"]
  },
  {
    "name": "SPAA 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-42 (Abstract)",
    "tags": ["#PARALLEL COMPUTING", "#ALGORITHMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 우수" },
    "abstract_deadline": "2026-02-20",
    "deadline": "2026-02-27",
    "notification": "2026-05-15",
    "conference_dates": "July 6-10, 2026",
    "location": "Raleigh, NC",
    "keywords": ["Parallel Algorithms", "Distributed Algorithms", "Complexity Theory"]
  },
  {
    "name": "Euro-Par 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-56",
    "tags": ["#PARALLEL COMPUTING", "#HIGH-PERFORMANCE COMPUTING"],
    "badges": { "bk_score": "BK21+ 1", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-06",
    "notification": "2026-04-30",
    "conference_dates": "August 24-28, 2026",
    "location": "Pisa, Italy",
    "keywords": ["Parallel Computing", "Distributed Systems", "High-Performance Computing", "Multi-core"]
  },
  {
    "name": "NSDI 2027",
    "link": null,
    "cycle": "Spring (Estimate)",
    "dDay": "D-60",
    "tags": ["#NETWORKED SYSTEMS", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-10",
    "notification": "2026-06-10",
    "conference_dates": "May 2027",
    "location": "TBD",
    "keywords": ["Networked Systems", "Cloud Networking", "Datacenters", "Distributed Systems"]
  },
  {
    "name": "ASPLOS 2027",
    "link": null,
    "cycle": "Spring",
    "dDay": "D-55 (Abstract)",
    "tags": ["#COMPUTER ARCHITECTURE", "#OPERATING SYSTEMS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-03-05",
    "deadline": "2026-03-12",
    "notification": "2026-06-24",
    "conference_dates": "March 30 - April 3, 2027",
    "location": "TBD",
    "keywords": ["Computer Architecture", "Operating Systems", "Compilers", "Hardware/Software Co-design"]
  },
  {
    "name": "MobiCom 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-63",
    "tags": ["#NETWORKING", "#MOBILE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-13",
    "notification": "2026-06-24",
    "conference_dates": "TBD",
    "location": "TBD",
    "keywords": ["Mobile Systems", "Wireless Networking"]
  },
  {
    "name": "LCTES 2026",
    "link": null,
    "cycle": "(Estimate)",
    "dDay": "D-57 (Abstract)",
    "tags": ["#EMBEDDED SYSTEMS", "#COMPILERS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": "2026-03-07",
    "deadline": "2026-03-14",
    "notification": "2026-04-21",
    "conference_dates": "June 15-16, 2026",
    "location": "Boulder, CO",
    "keywords": ["Embedded Systems", "Compiler Optimization", "Resource Management", "Real-Time Systems"]
  },
  {
    "name": "OOPSLA 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-67",
    "tags": ["#PROGRAMMING LANGUAGES", "#SOFTWARE ENGINEERING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-17",
    "notification": "2026-06-10",
    "conference_dates": "October 3-9, 2026",
    "location": "Oakland, CA",
    "keywords": ["Programming Models", "Software Engineering", "Language Design"]
  },
  {
    "name": "FAST 2026",
    "link": null,
    "cycle": "Spring",
    "dDay": "D-67",
    "tags": ["#STORAGE SYSTEMS", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-17",
    "notification": "2026-06-04",
    "conference_dates": "February 23-25, 2027",
    "location": "Renton, WA",
    "keywords": ["Storage Systems", "File Systems", "Non-volatile Memory"]
  },
  {
    "name": "ASE 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-76",
    "tags": ["#SOFTWARE ENGINEERING"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-26",
    "notification": "2026-06-18",
    "conference_dates": "October 12-16, 2026",
    "location": "Munich, Germany",
    "keywords": ["Software Engineering", "Automated Software Engineering", "Software Maintenance"],
    "extra": { "early_reject": "2026-05-25", "final": "2026-06-18" }
  },
  {
    "name": "EMSOFT 2026",
    "link": null,
    "cycle": "Journal Track",
    "dDay": "D-80",
    "tags": ["#EMBEDDED SYSTEMS", "#REAL-TIME SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2026-03-30",
    "notification": "2026-07-17",
    "conference_dates": "October 4-9, 2026",
    "location": "Barcelona, Spain",
    "keywords": ["Embedded Systems", "Cyber-Physical Systems", "Formal Verification"]
  },
  {
    "name": "SOSP 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-76 (Abstract)",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS", "#STORAGE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-03-26",
    "deadline": "2026-04-01",
    "notification": "2026-07-03",
    "conference_dates": "September 29 - October 2, 2026",
    "location": "Prague, Czech Republic",
    "keywords": ["Operating Systems", "Distributed Systems", "Storage Systems", "Cloud Computing"]
  },
  {
    "name": "SC 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-89",
    "tags": ["#HIGH-PERFORMANCE COMPUTING", "#NETWORKING", "#STORAGE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-04-08",
    "notification": "2026-07-01",
    "conference_dates": "November 15-20, 2026",
    "location": "Chicago, IL",
    "keywords": ["High-Performance Computing", "Supercomputing", "Data Analysis"]
  },
  {
    "name": "MICRO 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-92",
    "tags": ["#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-04-11",
    "notification": "2026-07-14",
    "conference_dates": "October 31 - November 4, 2026",
    "location": "Athens, Greece",
    "keywords": ["Microarchitecture", "Hardware Accelerators", "Computer Architecture", "Instruction-level Parallelism"]
  },
  {
    "name": "NDSS 2027",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D-98",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-04-17",
    "notification": "2026-06-20",
    "conference_dates": "February 21-25, 2027",
    "location": "San Diego, CA",
    "keywords": ["Network Security", "System Security", "Web Security"]
  },
  {
    "name": "SIGMOD 2027",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-91 (Abstract)",
    "tags": ["#DATA MANAGEMENT", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-04-10",
    "deadline": "2026-04-17",
    "notification": "2026-07-19",
    "conference_dates": "June 13-19, 2027",
    "location": "Huntington Beach, CA",
    "keywords": ["Databases", "Data Management", "Data Systems", "Scalable Data Processing"]
  },
  {
    "name": "PACT 2026",
    "link": null,
    "cycle": "(Estimate)",
    "dDay": "D-99",
    "tags": ["#PARALLEL COMPUTING", "#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-04-18",
    "notification": "2026-06-15",
    "conference_dates": "TBD",
    "location": "TBD",
    "keywords": ["Parallel Computing", "Compilers", "Parallel Architectures"]
  },
  {
    "name": "CCS 2026",
    "link": null,
    "cycle": "Cycle-2",
    "dDay": "D-103 (Abstract)",
    "tags": ["#COMPUTER SECURITY", "#NETWORK SECURITY"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-04-22",
    "deadline": "2026-04-29",
    "notification": "2026-07-17",
    "conference_dates": "November 15-19, 2026",
    "location": "The Hague, The Netherlands",
    "keywords": ["Computer Security", "Network Security", "Privacy", "Cryptography"],
    "extra": { "early_reject": "2026-06-03", "final": "2026-07-17" }
  },
  {
    "name": "ICPP 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-113",
    "tags": ["#PARALLEL COMPUTING", "#HIGH-PERFORMANCE COMPUTING"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2026-05-02",
    "notification": "July 2026",
    "conference_dates": "September 28 - October 1, 2026",
    "location": "Singapore",
    "keywords": ["Parallel Computing", "Parallel Algorithms", "Software Systems"]
  },
  {
    "name": "EuroSys 2026",
    "link": null,
    "cycle": "Spring",
    "dDay": "D-125",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-05-14",
    "notification": "2026-08-21",
    "conference_dates": "April 19-23, 2027",
    "location": "Morocco",
    "keywords": ["Distributed Systems", "Operating Systems", "Cloud Computing", "Virtualization"]
  },
  {
    "name": "RTSS 2026",
    "link": null,
    "cycle": null,
    "dDay": "D-132",
    "tags": ["#REAL-TIME SYSTEMS", "#EMBEDDED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-05-21",
    "notification": "July 2026",
    "conference_dates": "December 9-11, 2026",
    "location": "Yokohama, Japan",
    "keywords": ["Real-Time Systems", "Cyber-Physical Systems", "Embedded Systems", "IoT"]
  },
  {
    "name": "NeurIPS 2026",
    "link": null,
    "cycle": "(Estimate)",
    "dDay": "D-126 (Abstract)",
    "tags": [],
    "badges": { "bk_score": null, "kiise_score": null },
    "abstract_deadline": "2026-05-15",
    "deadline": "2026-05-22",
    "notification": "2026-09-24",
    "conference_dates": "December 6-12, 2026",
    "location": "Sydney, Australia",
    "keywords": []
  },
  {
    "name": "CoNEXT 2026",
    "link": null,
    "cycle": "Summer",
    "dDay": "D-147",
    "tags": ["#NETWORKING"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-06-05",
    "notification": "2026-09-11",
    "conference_dates": "December 7-10, 2026",
    "location": "Utrecht, The Netherlands",
    "keywords": ["Network Protocols", "Traffic Analysis", "Internet Architecture"]
  },
  {
    "name": "Middleware 2026",
    "link": null,
    "cycle": "Summer",
    "dDay": "D-147",
    "tags": ["#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 우수" },
    "abstract_deadline": null,
    "deadline": "2026-06-05",
    "notification": "2026-08-28",
    "conference_dates": "November 30 - December 4, 2026",
    "location": "Tarragona, Spain",
    "keywords": ["Distributed Systems", "Middleware", "Edge Computing"]
  },
  {
    "name": "IEEE S&P 2027",
    "link": null,
    "cycle": "Cycle-1",
    "dDay": "D-147 (Abstract)",
    "tags": ["#COMPUTER SECURITY"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-06-05",
    "deadline": "2026-06-12",
    "notification": "2026-09-08",
    "conference_dates": "May 17-21, 2027",
    "location": "San Francisco, CA",
    "keywords": ["System Security", "Privacy", "Cryptography", "Computer Security"]
  },
  {
    "name": "ICSE 2027",
    "link": null,
    "cycle": "Summer Cycle",
    "dDay": "D-157",
    "tags": ["#SOFTWARE ENGINEERING"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-06-15",
    "notification": "2026-11-01",
    "conference_dates": "April 25 - May 1, 2027",
    "location": "Dublin, Ireland",
    "keywords": ["Software Engineering", "Software Systems", "Software Quality"]
  },
  {
    "name": "SIGMOD 2027",
    "link": null,
    "cycle": "Cycle-3",
    "dDay": "D-182 (Abstract)",
    "tags": ["#DATA MANAGEMENT", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-07-10",
    "deadline": "2026-07-17",
    "notification": "2026-10-19",
    "conference_dates": "June 13-19, 2027",
    "location": "Huntington Beach, CA",
    "keywords": ["Databases", "Data Management", "Data Systems", "Scalable Data Processing"]
  },
  {
    "name": "HPCA 2027",
    "link": null,
    "cycle": null,
    "dDay": "D-204",
    "tags": ["#COMPUTER ARCHITECTURE"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-08-01",
    "notification": "2026-11-05",
    "conference_dates": "February 2027",
    "location": "TBD",
    "keywords": ["Computer Architecture", "Memory Hierarchy", "Multi-core", "Hardware Accelerators"]
  },
  {
    "name": "ASPLOS 2027",
    "link": null,
    "cycle": "Summer",
    "dDay": "D-216 (Abstract)",
    "tags": ["#COMPUTER ARCHITECTURE", "#OPERATING SYSTEMS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-08-13",
    "deadline": "2026-08-20",
    "notification": "2026-11-24",
    "conference_dates": "March 30 - April 3, 2027",
    "location": "TBD",
    "keywords": ["Computer Architecture", "Operating Systems", "Compilers", "Hardware/Software Co-design"]
  },
  {
    "name": "FAST 2027",
    "link": null,
    "cycle": "Fall",
    "dDay": "D-249",
    "tags": ["#STORAGE SYSTEMS", "#OPERATING SYSTEMS"],
    "badges": { "bk_score": "BK21+ 3", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-09-15",
    "notification": "2026-12-08",
    "conference_dates": "February 23-25, 2027",
    "location": "Renton, WA",
    "keywords": ["Storage Systems", "File Systems", "Non-volatile Memory"]
  },
  {
    "name": "EuroSys 2027",
    "link": null,
    "cycle": "Fall",
    "dDay": "D-258",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-09-24",
    "notification": "2027-01-29",
    "conference_dates": "April 19-23, 2027",
    "location": "Morocco",
    "keywords": ["Distributed Systems", "Operating Systems", "Cloud Computing", "Virtualization"]
  },
  {
    "name": "EuroSys 2027",
    "link": null,
    "cycle": "Fall (Estimate)",
    "dDay": "D-258",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 2", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-09-24",
    "notification": "2027-01-29",
    "conference_dates": "April 2027",
    "location": "Morocco",
    "keywords": ["Distributed Systems", "Operating Systems", "Cloud Computing", "Virtualization"]
  },
  {
    "name": "SIGMOD 2027",
    "link": null,
    "cycle": "Cycle-4",
    "dDay": "D-274 (Abstract)",
    "tags": ["#DATA MANAGEMENT", "#DISTRIBUTED SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": "2026-10-10",
    "deadline": "2026-10-17",
    "notification": "2027-01-19",
    "conference_dates": "June 13-19, 2027",
    "location": "Huntington Beach, CA",
    "keywords": ["Databases", "Data Management", "Data Systems", "Scalable Data Processing"]
  },
  {
    "name": "ASPLOS 2027",
    "link": null,
    "cycle": "Fall (Estimate)",
    "dDay": "D-284",
    "tags": ["#COMPUTER ARCHITECTURE", "#OPERATING SYSTEMS", "#PROGRAMMING LANGUAGES"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-10-20",
    "notification": "2027-01-24",
    "conference_dates": "TBD",
    "location": "TBD",
    "keywords": ["Computer Architecture", "Operating Systems", "Compilers", "Hardware/Software Co-design"]
  },
  {
    "name": "OSDI 2027",
    "link": null,
    "cycle": null,
    "dDay": "D-336",
    "tags": ["#OPERATING SYSTEMS", "#DISTRIBUTED SYSTEMS", "#STORAGE SYSTEMS"],
    "badges": { "bk_score": "BK21+ 4", "kiise_score": "KIISE 최우수" },
    "abstract_deadline": null,
    "deadline": "2026-12-11",
    "notification": "March 2027",
    "conference_dates": "July 2027",
    "location": "TBD",
    "keywords": ["Operating Systems", "Distributed Systems", "Storage Systems", "Cloud Computing", "Reliability"]
  }
];